version: "3.8"
services:
    database:
        image: postgres:9.6
        container_name: database
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: kerb
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - "54322:5432"
    app:
        container_name: kerb-app
        build: .
        command: php artisan schedule:work
        ports:
            - "8000:80"
        volumes:
            - ./src:/var/www/kerb
            - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
        depends_on:
            - database
